stages:
  - construction
  - deploy

composer installation api:
  image: pockost/php:8.2-cli-bookworm
  stage: construction
  only:
    changes:
      - composer.json
      - composer.lock

  script:
    - composer install --no-scripts --no-dev --optimize-autoloader --no-interaction
  artifacts:
    paths:
      - vendor/

deploiement de la partie api avec les vendor:
  image:
    name: pockost/phploy:4.9.3
    entrypoint:  [""]
  stage: deploy
  only:
    changes:
      - composer.json
      - composer.lock
  script:
    - phploy -s api-prod-with-vendor



deploiement de la partie api sans les vendor:
  image:
    name: pockost/phploy:4.9.3
    entrypoint:  [""]
  stage: deploy
  except:
    changes:
      - composer.json
      - composer.lock
  script:
    - phploy -s api-prod-without-vendor

